#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "layout.h"

#define TAMBUFF 109000
 
int segmento_inicial(char *b, size_t s){

    //buffer que conterá o texto
    char buffer[TAMBUFF];
    buffer[0] = '\x0';

    //segmento inicial do html
    strncpy(buffer,
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"\r\n"
"<!--\r\n"
"Layout: https://github.com/daniguerrato/design-responsivo-demo\r\n"
"-->\r\n"
"\r\n"
"<head>\r\n"
"<meta charset=\"UTF-8\">\r\n"
"<title>EC8TOP</title>\r\n"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
"<link rel=\"icon\" href=\"images/favicon.png\" type=\"image/x-icon\"/>\r\n"
"<link rel=\"shortcut icon\" href=\"images/favicon.png\" type=\"image/x-icon\"/>\r\n"
"<style>\r\n"
"\r\n"
"article,\r\n"
"aside,\r\n"
"details,\r\n"
"figcaption,\r\n"
"figure,\r\n"
"footer,\r\n"
"header,\r\n"
"hgroup,\r\n"
"main,\r\n"
"section,\r\n"
"summary {\r\n"
"display: block;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Correct `inline-block` display not defined in IE 6/7/8/9 and Firefox 3.\r\n"
"*/\r\n"
"\r\n"
"audio,\r\n"
"canvas,\r\n"
"video {\r\n"
"display: inline-block;\r\n"
"*display: inline;\r\n"
"*zoom: 1;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Prevent modern browsers from displaying `audio` without controls.\r\n"
"* Remove excess height in iOS 5 devices.\r\n"
"*/\r\n"
"\r\n"
"audio:not([controls]) {\r\n"
"display: none;\r\n"
"height: 0;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address styling not present in IE 7/8/9, Firefox 3, and Safari 4.\r\n"
"* Known issue: no IE 6 support.\r\n"
"*/\r\n"
"\r\n"
"[hidden] {\r\n"
"display: none;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Base\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* 1. Prevent system color scheme's background color being used in Firefox, IE,\r\n"
"*    and Opera.\r\n"
"* 2. Prevent system color scheme's text color being used in Firefox, IE, and\r\n"
"*    Opera.\r\n"
"* 3. Correct text resizing oddly in IE 6/7 when body `font-size` is set using\r\n"
"*    `em` units.\r\n"
"* 4. Prevent iOS text size adjust after orientation change, without disabling\r\n"
"*    user zoom.\r\n"
"*/\r\n"
"\r\n"
"html {\r\n"
"background: #fff; /* 1 */\r\n"
"color: #000; /* 2 */\r\n"
"-webkit-text-size-adjust: 100%%; /* 4 */\r\n"
"-ms-text-size-adjust: 100%%; /* 4 */\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address `font-family` inconsistency between `textarea` and other form\r\n"
"* elements.\r\n"
"*/\r\n"
"\r\n"
"html,\r\n"
"button,\r\n"
"input,\r\n"
"select,\r\n"
"textarea {\r\n"
"font-family: sans-serif;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address margins handled incorrectly in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"body {\r\n"
"margin: 0;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Links\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* Address `outline` inconsistency between Chrome and other browsers.\r\n"
"*/\r\n"
"\r\n"
"a:focus {\r\n"
"outline: thin dotted;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Improve readability when focused and also mouse hovered in all browsers.\r\n"
"*/\r\n"
"\r\n"
"a:active,\r\n"
"a:hover {\r\n"
"outline: 0;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Typography\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* Address font sizes and margins set differently in IE 6/7.\r\n"
"* Address font sizes within `section` and `article` in Firefox 4+, Safari 5,\r\n"
"* and Chrome.\r\n"
"*/\r\n"
"\r\n"
"h1 {\r\n"
"font-size: 2em;\r\n"
"margin: 0.67em 0;\r\n"
"}\r\n"
"\r\n"
"h2 {\r\n"
"font-size: 1.5em;\r\n"
"margin: 0.83em 0;\r\n"
"}\r\n"
"\r\n"
"h3 {\r\n"
"font-size: 1.17em;\r\n"
"margin: 1em 0;\r\n"
"}\r\n"
"\r\n"
"h4 {\r\n"
"font-size: 1em;\r\n"
"margin: 1.33em 0;\r\n"
"}\r\n"
"\r\n"
"h5 {\r\n"
"font-size: 0.83em;\r\n"
"margin: 1.67em 0;\r\n"
"}\r\n"
"\r\n"
"h6 {\r\n"
"font-size: 0.67em;\r\n"
"margin: 2.33em 0;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address styling not present in IE 7/8/9, Safari 5, and Chrome.\r\n"
"*/\r\n"
"\r\n"
"abbr[title] {\r\n"
"border-bottom: 1px dotted;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address style set to `bolder` in Firefox 3+, Safari 4/5, and Chrome.\r\n"
"*/\r\n"
"\r\n"
"b,\r\n"
"strong {\r\n"
"font-weight: bold;\r\n"
"}\r\n"
"\r\n"
"blockquote {\r\n"
"margin: 1em 40px;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address styling not present in Safari 5 and Chrome.\r\n"
"*/\r\n"
"\r\n"
"dfn {\r\n"
"font-style: italic;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address differences between Firefox and other browsers.\r\n"
"* Known issue: no IE 6/7 normalization.\r\n"
"*/\r\n"
"\r\n"
"hr {\r\n"
"-moz-box-sizing: content-box;\r\n"
"box-sizing: content-box;\r\n"
"height: 0;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address styling not present in IE 6/7/8/9.\r\n"
"*/\r\n"
"\r\n"
"mark {\r\n"
"background: #ff0;\r\n"
"color: #000;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address margins set differently in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"p,\r\n"
"pre {\r\n"
"margin: 1em 0;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Correct font family set oddly in IE 6, Safari 4/5, and Chrome.\r\n"
"*/\r\n"
"\r\n"
"code,\r\n"
"kbd,\r\n"
"pre,\r\n"
"samp {\r\n"
"font-family: monospace, serif;\r\n"
"_font-family: 'courier new', monospace;\r\n"
"font-size: 1em;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Improve readability of pre-formatted text in all browsers.\r\n"
"*/\r\n"
"\r\n"
"pre {\r\n"
"white-space: pre;\r\n"
"white-space: pre-wrap;\r\n"
"word-wrap: break-word;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address CSS quotes not supported in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"q {\r\n"
"quotes: none;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address `quotes` property not supported in Safari 4.\r\n"
"*/\r\n"
"\r\n"
"q:before,\r\n"
"q:after {\r\n"
"content: '';\r\n"
"content: none;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address inconsistent and variable font size in all browsers.\r\n"
"*/\r\n"
"\r\n"
"small {\r\n"
"font-size: 80%%;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Prevent `sub` and `sup` affecting `line-height` in all browsers.\r\n"
"*/\r\n"
"\r\n"
"sub,\r\n"
"sup {\r\n"
"font-size: 75%%;\r\n"
"line-height: 0;\r\n"
"position: relative;\r\n"
"vertical-align: baseline;\r\n"
"}\r\n"
"\r\n"
"sup {\r\n"
"top: -0.5em;\r\n"
"}\r\n"
"\r\n"
"sub {\r\n"
"bottom: -0.25em;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Lists\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* Address margins set differently in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"dl,\r\n"
"menu,\r\n"
"ol,\r\n"
"ul {\r\n"
"margin: 1em 0;\r\n"
"}\r\n"
"\r\n"
"dd {\r\n"
"margin: 0 0 0 40px;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address paddings set differently in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"menu,\r\n"
"ol,\r\n"
"ul {\r\n"
"padding: 0 0 0 40px;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Correct list images handled incorrectly in IE 7.\r\n"
"*/\r\n"
"\r\n"
"nav ul,\r\n"
"nav ol {\r\n"
"list-style: none;\r\n"
"list-style-image: none;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Embedded content\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* 1. Remove border when inside `a` element in IE 6/7/8/9 and Firefox 3.\r\n"
"* 2. Improve image quality when scaled in IE 7.\r\n"
"*/\r\n"
"\r\n"
"img {\r\n"
"border: 0; /* 1 */\r\n"
"-ms-interpolation-mode: bicubic; /* 2 */\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Correct overflow displayed oddly in IE 9.\r\n"
"*/\r\n"
"\r\n"
"svg:not(:root) {\r\n"
"overflow: hidden;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Figures\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* Address margin not present in IE 6/7/8/9, Safari 5, and Opera 11.\r\n"
"*/\r\n"
"\r\n"
"figure {\r\n"
"margin: 0;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Forms\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* Correct margin displayed oddly in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"form {\r\n"
"margin: 0;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Define consistent border, margin, and padding.\r\n"
"*/\r\n"
"\r\n"
"fieldset {\r\n"
"border: 1px solid #c0c0c0;\r\n"
"margin: 0 2px;\r\n"
"padding: 0.35em 0.625em 0.75em;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* 1. Correct color not being inherited in IE 6/7/8/9.\r\n"
"* 2. Correct text not wrapping in Firefox 3.\r\n"
"* 3. Correct alignment displayed oddly in IE 6/7.\r\n"
"*/\r\n"
"\r\n"
"legend {\r\n"
"border: 0; /* 1 */\r\n"
"padding: 0;\r\n"
"white-space: normal; /* 2 */\r\n"
"*margin-left: -7px; /* 3 */\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* 1. Correct font size not being inherited in all browsers.\r\n"
"* 2. Address margins set differently in IE 6/7, Firefox 3+, Safari 5,\r\n"
"*    and Chrome.\r\n"
"* 3. Improve appearance and consistency in all browsers.\r\n"
"*/\r\n"
"\r\n"
"button,\r\n"
"input,\r\n"
"select,\r\n"
"textarea {\r\n"
"font-size: 100%%; /* 1 */\r\n"
"margin: 0; /* 2 */\r\n"
"vertical-align: baseline; /* 3 */\r\n"
"*vertical-align: middle; /* 3 */\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address Firefox 3+ setting `line-height` on `input` using `!important` in\r\n"
"* the UA stylesheet.\r\n"
"*/\r\n"
"\r\n"
"button,\r\n"
"input {\r\n"
"line-height: normal;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Address inconsistent `text-transform` inheritance for `button` and `select`.\r\n"
"* All other form control elements do not inherit `text-transform` values.\r\n"
"* Correct `button` style inheritance in Chrome, Safari 5+, and IE 6+.\r\n"
"* Correct `select` style inheritance in Firefox 4+ and Opera.\r\n"
"*/\r\n"
"\r\n"
"button,\r\n"
"select {\r\n"
"text-transform: none;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`\r\n"
"*    and `video` controls.\r\n"
"* 2. Correct inability to style clickable `input` types in iOS.\r\n"
"* 3. Improve usability and consistency of cursor style between image-type\r\n"
"*    `input` and others.\r\n"
"* 4. Remove inner spacing in IE 7 without affecting normal text inputs.\r\n"
"*    Known issue: inner spacing remains in IE 6.\r\n"
"*/\r\n"
"\r\n"
"button,\r\n"
"html input[type=\"button\"], /* 1 */\r\n"
"input[type=\"reset\"],\r\n"
"input[type=\"submit\"] {\r\n"
"-webkit-appearance: button; /* 2 */\r\n"
"cursor: pointer; /* 3 */\r\n"
"*overflow: visible;  /* 4 */\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Re-set default cursor for disabled elements.\r\n"
"*/\r\n"
"\r\n"
"button[disabled],\r\n"
"html input[disabled] {\r\n"
"cursor: default;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* 1. Address box sizing set to content-box in IE 8/9.\r\n"
"* 2. Remove excess padding in IE 8/9.\r\n"
"* 3. Remove excess padding in IE 7.\r\n"
"*    Known issue: excess padding remains in IE 6.\r\n"
"*/\r\n"
"\r\n"
"input[type=\"checkbox\"],\r\n"
"input[type=\"radio\"] {\r\n"
"box-sizing: border-box; /* 1 */\r\n"
"padding: 0; /* 2 */\r\n"
"*height: 13px; /* 3 */\r\n"
"*width: 13px; /* 3 */\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* 1. Address `appearance` set to `searchfield` in Safari 5 and Chrome.\r\n"
"* 2. Address `box-sizing` set to `border-box` in Safari 5 and Chrome\r\n"
"*    (include `-moz` to future-proof).\r\n"
"*/\r\n"
"\r\n"
"input[type=\"search\"] {\r\n"
"-webkit-appearance: textfield; /* 1 */\r\n"
"-moz-box-sizing: content-box;\r\n"
"-webkit-box-sizing: content-box; /* 2 */\r\n"
"box-sizing: content-box;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Remove inner padding and search cancel button in Safari 5 and Chrome\r\n"
"* on OS X.\r\n"
"*/\r\n"
"\r\n"
"input[type=\"search\"]::-webkit-search-cancel-button,\r\n"
"input[type=\"search\"]::-webkit-search-decoration {\r\n"
"-webkit-appearance: none;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* Remove inner padding and border in Firefox 3+.\r\n"
"*/\r\n"
"\r\n"
"button::-moz-focus-inner,\r\n"
"input::-moz-focus-inner {\r\n"
"border: 0;\r\n"
"padding: 0;\r\n"
"}\r\n"
"\r\n"
"/**\r\n"
"* 1. Remove default vertical scrollbar in IE 6/7/8/9.\r\n"
"* 2. Improve readability and alignment in all browsers.\r\n"
"*/\r\n"
"\r\n"
"textarea {\r\n"
"overflow: auto; /* 1 */\r\n"
"vertical-align: top; /* 2 */\r\n"
"}\r\n"
"\r\n"
"/*Retira cantos arredondados em formulÃ¡rios do iOS*/\r\n"
"input[type=\"text\"],\r\n"
"input[type=\"submit\"],\r\n"
"textarea {\r\n"
"-webkit-appearance: none;\r\n"
"-webkit-border-radius: 0;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Tables\r\n"
"========================================================================== */\r\n"
"\r\n"
"/**\r\n"
"* Remove most spacing between table cells.\r\n"
"*/\r\n"
"\r\n"
"table {\r\n"
"border-collapse: collapse;\r\n"
"border-spacing: 0;\r\n"
"}\r\n"
"\r\n"
"fieldset {\r\n"
"border: 0;\r\n"
"margin: 0;\r\n"
"padding: 0;\r\n"
"}\r\n"
"\r\n"
"textarea {\r\n"
"resize: vertical;\r\n"
"}\r\n"
"\r\n"
"nav{\r\n"
"list-style: none;\r\n"
"position: fixed;\r\n"
"right: 0.4em;\r\n"
"}\r\n"
"\r\n"
"nav ul, nav li {\r\n"
"margin: 0;\r\n"
"padding: 0;\r\n"
"}\r\n"
"\r\n"
"nav a{\r\n"
"display:block;\r\n"
"width: 15px;\r\n"
"height: 15px;\r\n"
"margin: 5px;;\r\n"
"text-decoration:none;\r\n"
"background-color:#ddd;\r\n"
"border:2px solid #333;\r\n"
"\r\n"
"border-radius:50%%;\r\n"
"-moz-border-radius:50%%;\r\n"
"-webkit-border-radius:50%%;\r\n"
"}\r\n"
"/* ==========================================================================\r\n"
"NormatizaÃ§Ã£o CSS\r\n"
"========================================================================== */\r\n"
"\r\n"
"body {\r\n"
"font-size: 62.5%%;\r\n"
"line-height: 1.5;\r\n"
"font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n"
"color: #444;\r\n"
"}\r\n"
"\r\n"
"*, *:before, *:after {\r\n"
"-webkit-box-sizing: border-box;\r\n"
"-moz-box-sizing: border-box;\r\n"
"box-sizing: border-box;\r\n"
"}\r\n"
"\r\n"
"a {\r\n"
"color: #00ccff;\r\n"
"text-decoration: none;\r\n"
"font-size: 1.6em;\r\n"
"}\r\n"
"\r\n"
"\r\n"
"\r\n"
"/* ==|== Estilos Principais ================================================== */\r\n"
"\r\n"
".container {\r\n"
"max-width: 1128px;\r\n"
"margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
"img,\r\n"
"picture,\r\n"
"video,\r\n"
"embed {\r\n"
"max-width: 100%%;\r\n"
"}\r\n"
"\r\n"
".header {\r\n"
"width: 100%%;\r\n"
"height: 40px;\r\n"
"margin-top: 3.6em;\r\n"
"margin-bottom: 3.6em;\r\n"
"}\r\n"
"\r\n"
".logo {\r\n"
"float: left;\r\n"
"width: 20.744680851064%%; /*234px / 1128px */\r\n"
"-webkit-background-clip: text;\r\n"
"-moz-background-clip: text;\r\n"
"background-clip: text;\r\n"
"color: #888;\r\n"
"text-shadow: rgba(0,0,0,0.5) 0px 3px 3px;\r\n"
"}\r\n"
"\r\n"
"h1  {\r\n"
"margin-top: 0;\r\n"
"margin-bottom: 0;\r\n"
"font-size: 4em;\r\n"
"font-weight: 200;\r\n"
"color: #FFF;\r\n"
"}\r\n"
"\r\n"
"strong{\r\n"
"font-size: 2em;\r\n"
"}\r\n"
"\r\n"
".coluna {\r\n"
"width: 23.404255319149%%; /* 264px / 1128px */\r\n"
"float: left;\r\n"
"margin-right: 2.127659574468%%; /* 24 / 1128px */\r\n"
"}\r\n"
"\r\n"
".coluna:last-child {\r\n"
"margin-right: 0;\r\n"
"}\r\n"
"\r\n"
"h2 {\r\n"
"font-size: 2.4em;\r\n"
"font-weight: 200;\r\n"
"}\r\n"
"\r\n"
"p {\r\n"
"font-size: 1.6em;\r\n"
"}\r\n"
"\r\n"
".footer {\r\n"
"width: 100%%;\r\n"
"margin-top: 2.4em;\r\n"
"margin-bottom: 0px;\r\n"
"float: left;\r\n"
"clear: both;\r\n"
"background:#000;\r\n"
"color:#fff;\r\n"
"padding:2.8em;\r\n"
"}\r\n"
"\r\n"
".footer div{\r\n"
"max-width: 1128px;\r\n"
"margin: 0 auto;\r\n"
"}\r\n"
"\r\n"
".footer p {\r\n"
"margin-bottom: 0;\r\n"
"}\r\n"
"\r\n"
".footer h2 {\r\n"
"font-size: 1.8em;\r\n"
"text-decoration:none;\r\n"
"margin:0px;\r\n"
"}\r\n"
"\r\n"
".footer a {\r\n"
"text-decoration:none;\r\n"
"color:#aaa;\r\n"
"}\r\n"
"\r\n"
".footer a:hover{\r\n"
"color:#fff;\r\n"
"}\r\n"
"\r\n"
".linha{\r\n"
"padding:0;\r\n"
"clear:both;\r\n"
"display: table-row;\r\n"
"}\r\n"
"\r\n"
".celula{\r\n"
"display: table-cell;\r\n"
"clear: both;\r\n"
"padding:0.5em;\r\n"
"}\r\n"
".tabela{\r\n"
"display:table;\r\n"
"width:100%%;\r\n"
"text-align:center;\r\n"
"}\r\n"
"\r\n"
".bloco{\r\n"
"text-align:left;\r\n"
"display:inline-block;\r\n"
"vertical-align: text-top;\r\n"
"}\r\n"
"\r\n"
"/* ==========================================================================\r\n"
"Media Queries\r\n"
"========================================================================== */\r\n"
"\r\n"
"\r\n"
"@media screen and (max-width: 1128px) {\r\n"
"\r\n"
".container {\r\n"
"padding: 0 2.4em 0 2.4em;\r\n"
"}\r\n"
"\r\n"
"}\r\n"
"\r\n"
"@media screen and (max-width: 768px) {\r\n"
"\r\n"
"\r\n"
".coluna {\r\n"
"width: 48%%;\r\n"
"margin-bottom: 2.4em;\r\n"
"margin-right: 2%%;\r\n"
"}\r\n"
"\r\n"
".coluna:nth-child(even) {\r\n"
"margin-right: 0;\r\n"
"}\r\n"
"\r\n"
"}\r\n"
"\r\n"
"@media screen and (max-width: 520px) {\r\n"
"\r\n"
".coluna {\r\n"
"width: 100%%;\r\n"
"margin-right: 0;\r\n"
"}\r\n"
"\r\n"
".celula{\r\n"
"float:left;\r\n"
"}\r\n"
"\r\n"
".tabela{\r\n"
"text-align:left;\r\n"
"}\r\n"
"\r\n"
"}\r\n"
"\r\n"
".clearfix:before,\r\n"
".clearfix:after {\r\n"
"content: \" \";\r\n"
"display: table;\r\n"
"}\r\n"
"\r\n"
".clearfix:after {\r\n"
"clear: both;\r\n"
"}\r\n"
"\r\n"
".clearfix {\r\n"
"*zoom: 1;\r\n"
"}\r\n"
"\r\n"
"</style>\r\n"
"</head>\r\n"
"\r\n"
"<body>\r\n"
"<div class=\"container clearfix\">\r\n"
"<header class=\"header\">\r\n"
"<h1 class=\"logo\">EC8TOP</h1>\r\n"
"<nav>\r\n"
"<ul>\r\n"
"<li><a href=\"#versao\" title=\"Sistema Operacional\"> </a></li>\r\n"
"<li><a href=\"#processos\" title=\"Processos executados\"> </a></li>\r\n"
"<li><a href=\"#memoria\" title=\"Memória RAM\"> </a></li>\r\n"
"<li><a href=\"#bateria\" title=\"Nível da bateria\"> </a></li>\r\n"
"<li><a href=\"#sobre\" title=\"Sobre nós\"> </a></li>\r\n"
"</ul>\r\n"
"</nav>\r\n"
"</header>\r\n"
"<section class=\"principal\">\r\n"
	,sizeof(buffer));

	strncat(b, buffer, s);  
	return 1;
}

int segmento_final(char *b, size_t s){

    //buffer que conterá o texto
    char buffer[TAMBUFF];
    buffer[0] = '\x0';

    // segmento final do html
    strncpy(buffer,    
"</section>\r\n"
"\r\n"
"</div>\r\n"
"\r\n"
"<footer id='sobre' class=\"footer\">\r\n"
"\r\n"
"<div>\r\n"
"<h2>ec8top <small>5/10/14</small></h2>\r\n"
"<figure class=\"foto\"><img src=\"images/git.png\"></figure>\r\n"
"<strong>GitHub</strong>: <a href=\"https://github.com/trumae/ec8top\" title=\"Siga nosso projeto no GitHub\">trumae/ec8top</a>\r\n"
"</div>\r\n"
"\r\n"
"<div class='tabela'>\r\n"
"<div class='linha'>\r\n"
"\r\n"
"<div class=\"celula\">\r\n"
"<div class='bloco'>\r\n"
"<h2>Administração</h2>\r\n"
"<div>\r\n"
"<a href=\"https://github.com/bruunamiranda\">Bruna</a></div><div>\r\n"
"<a href=\"https://github.com/MatheusAvelino\">Matheus</a></div>\r\n"
"</div>\r\n"
"</div>\r\n"
"\r\n"
"<div class=\"celula\">\r\n"
"<div class='bloco'>\r\n"
"<h2>Desenvolvimento / Codificação</h2>\r\n"
"<div>\r\n"
"<a href=\"https://github.com/lms91\">Leandro</a></div><div>\r\n"
"<a href=\"https://github.com/htg90\">Helbert</a></div><div>\r\n"
"<a href=\"https://github.com/RIPOP\">Rodrigo</a></div><div>\r\n"
"<a href=\"https://github.com/nilsonec2015\">Nilson</a></div><div>\r\n"
"<a href=\"https://github.com/Danilofn\">Danilo</a></div><div>\r\n"
"<a href=\"https://github.com/EliasThiago\">Thiago</a></div><div>\r\n"
"<a href=\"https://github.com/sousa-lucas\">Lucas</a></div><div>\r\n"
"<a href=\"https://github.com/GuilhermeBastos\">Guilherme</a></div>\r\n"
"</div>\r\n"
"</div>\r\n"
"\r\n"
"<div class=\"celula\">\r\n"
"<div class='bloco'>\r\n"
"<h2>Documentação</h2>\r\n"
"<div>\r\n"
"<a href=\"https://github.com/Nayara22\">Nayara</a></div><div>\r\n"
"<a href=\"https://github.com/tlimaa\">Thaina</a></div><div>\r\n"
"<a href=\"https://github.com/weltonsiqueira\">Welton</a></div><div>\r\n"
"<a href=\"https://github.com/marciaoliveira\">M&aacutercia</a></div>\r\n"
"</div>\r\n"
"</div>\r\n"
"\r\n"
"</div>\r\n"
"</div>\r\n"
"</footer>\r\n"
"\r\n"
"</body>\r\n"
"</html>\r\n"
	,sizeof(buffer));   

	strncat(b, buffer, s);  
    //retorna sucesso
    return 1;
}
